In [70]:
from bs4 import BeautifulSoup
import requests
import itertools
import pandas as pd

url = "http://www.donbest.com/mlb/odds/money-lines/20170805.html"
r  = requests.get(url)
data = r.text
soup = BeautifulSoup(data, 'html.parser')

In [71]:
odds = soup.find("div", {"class": "odds_gamesHolder"})
left_games = soup.find_all("td", {"class":"alignLeft"})
center_games = soup.find_all("td", {"class":"alignCenter"})
right_games = soup.find_all("td", {"class":"alignRight"})
game_count = -1

df = pd.DataFrame(columns=['Away_Team','Home_Team','Away_Starter','Home_Starter','Start_Time','Away_Final_Score','Home_Final_Score', 'Away_Opening', 'Home_Opening', 'Away_Westgate', 
    'Home_Westgate', 'Away_Mirage', 'Home_Mirage', 'Away_Station', 'Home_Station', 'Away_Pinnacle', 'Home_Pinnacle', 'Away_SIA', 'Home_SIA', 'Away_SBG', 'Home_SBG', 
        'Away_BetUS', 'Home_BetUS', 'Away_BetPhoenix', 'Home_BetPhoenix', 'Away_EasyStreet', 'Home_EasyStreet', 'Away_Bovada', 'Home_Bovada', 'Away_Jazz', 'Home_Jazz',
            'Away_Sportsbet', 'Home_Sportsbet', 'Away_Bookmaker', 'Home_Bookmaker', 'Away_DSI', 'Home_DSI', 'Away_AceSport', 'Home_AceSport'])

teams = ['Away_Team','Home_Team']
starter = ['Away_Starter','Home_Starter']
center_cols = ['Start_Time', 'Away_Final_Score', 'Home_Final_Score']
sportsbooks = ['Away_Westgate', 'Home_Westgate', 'Away_Mirage', 'Home_Mirage', 'Away_Station', 'Home_Station', 'Away_Pinnacle', 'Home_Pinnacle', 'Away_SIA', 'Home_SIA', 'Away_SBG', 'Home_SBG', 
        'Away_BetUS', 'Home_BetUS', 'Away_BetPhoenix', 'Home_BetPhoenix', 'Away_EasyStreet', 'Home_EasyStreet', 'Away_Bovada', 'Home_Bovada', 'Away_Jazz', 'Home_Jazz',
            'Away_Sportsbet', 'Home_Sportsbet', 'Away_Bookmaker', 'Home_Bookmaker', 'Away_DSI', 'Home_DSI', 'Away_AceSport', 'Home_AceSport']

In [72]:
##  Game Time / Score ##
skip_every_third = 1
row = 0
pos = 0
inc_row = False

for center in center_games:
    scores = center.find_all("div")
    if skip_every_third % 3 != 0:
        for score in scores:
            df.at[row, center_cols[pos]] = score.text
            pos = pos + 1
        if not inc_row:
            inc_row = True
        else:
            inc_row = False
            row = row + 1
            pos = 0
    skip_every_third = skip_every_third + 1

In [73]:
df.head(50)

,Away_Team,Home_Team,Away_Starter,Home_Starter,Start_Time,Away_Final_Score,Home_Final_Score,Away_Opening,Home_Opening,Away_Westgate,...,Away_Jazz,Home_Jazz,Away_Sportsbet,Home_Sportsbet,Away_Bookmaker,Home_Bookmaker,Away_DSI,Home_DSI,Away_AceSport,Home_AceSport
0,NaN,NaN,NaN,NaN,2:20 PM,4,7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,4:05 PM,7,4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,7:30 PM,5,2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,7:10 PM,2,7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,7:10 PM,4,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,8:10 PM,5,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,9:10 PM,4,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,7:05 PM,2,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,7:10 PM,1,4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,7:10 PM,4,3,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,7:10 PM,2,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,7:55 PM,4,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,PP,-,-,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,9:05 PM,5,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,6:10 PM,3,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
## Starter Names / Team Names / Game Lines ##
row = 0
for left in left_games:

    game_count = game_count + 1
    div = left.find_all("div")
    span = left.find_all("span")
    skip = True
    pos = 0
    
    for playername in div:
        if skip:
            skip = False
        else:
            df.at[row, starter[pos]] = playername.text
            pos = pos + 1

    pos = 0
    for teamname in span:
        df.at[row, teams[pos]] = teamname.text
        pos = pos + 1

    first = True
    pos = 0
    for x in range(0, 17):
        lines = right_games[x+(game_count*17)].find_all("div")
        for line in lines:
            if first:
                first = False
                df.at[row, 'Away_Opening'] = (line.text)[:-4]
                df.at[row, 'Home_Opening'] = (line.text)[4:]
            else:
                df.at[row, sportsbooks[pos]] = line.text
                pos = pos + 1
    row = row + 1